import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
import MainNavBar from "./components/navbar/MainNavbar";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { ReduxProviders } from "@/app/reduxProviders";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <ReduxProviders>
            <Providers>
              <MainNavBar />
              {children}
            </Providers>
          </ReduxProviders>
        </NextIntlClientProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
